export { ShowTicketPage } from './orders/show-ticket/show-ticket';
export { AcceptOrderPage } from './core-app/accept-order/accept-order';
export { DriverOrderPage } from './core-app/driver-order/driver-order';
export { DriverOrderCompletedPage } from './core-app/driver-order-completed/driver-order-completed';
export { DriverRatingPage } from './core-app/driver-rating/driver-rating';
export { LobbyPage } from './core-app/lobby/lobby';
export { HelpPage } from './help/help/help';
export { HelpCenterPage } from './help/help-center/help-center';
export { PrivacyPage } from './help/privacy/privacy';
export { TermsConditionsPage } from './help/terms-conditions/terms-conditions';
export { EmployeeCodePage } from './login/employee-code/employee-code';
export { PasswordPage } from './login/password/password';
export { MenuPage } from './menu/menu';
export { PastOrdersPage} from './orders/past-orders/past-orders';
export { MyOrdersPage} from './orders/my-orders/my-orders';
export { PastOrdersDetailPage} from './orders/past-orders-detail/past-orders-detail';
export { UpcomingOrdersPage} from './orders/upcoming-orders/upcoming-orders';
export { UpcomingOrdersDetailPage} from './orders/upcoming-orders-detail/upcoming-orders-detail';
export { NavigationSettingsPage } from './setting/navigation-settings/navigation-settings';
export { SettingsPage } from './setting/settings/settings';
export { VehicleManagerPage } from "./setting/vehicle-manager/vehicle-manager";
export { DriverRegisterPage } from "./login/driver-register/driver-register";
export { VehicleRegisterPage } from "./login/vehicle-register/vehicle-register";